modLoader="javafml"
loaderVersion="*"
license="All rights reserved"
issueTrackerURL="https://github.com/Serilum/.issue-tracker/labels/Mod:%20Welcome%20Message"
logoFile="icon.png"

[[mods]]
modId="welcomemessage"
version="2.6"
displayName="Welcome Message"
displayURL="https://serilum.com/mod/welcome-message"
authors="Rick South"
description='''An easy to configure welcome message mod for players after login with URL support.
'''
credits='''Thank you very much to my Membership sponsors for supporting the development of this mod:  

Alister, Andrean Olgo, aternosorg, Cherriesaurus, Michael W. S., Nahuel Fernandez, Shana Gitnick, Tyler Behl   

If you would like to contribute too, check out https://serilum.com/donate. Appreciate it! <3   
'''

[[dependencies.welcomemessage]]
    modId="collective"
    mandatory=true
    versionRange="[7.80,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.welcomemessage]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.21,1.21.1]"
    ordering="NONE"
    side="BOTH"
